### ISSUE TITLE
Inconsistent information on which version of Flocker the driver was tested against

### ISSUE THREAD

**Issue by ferrantim** [dellstorage/storagecenter-flocker-driver#1]
Hi @stmcginnis,

I hope you're about to take some well deserved time off this year.  In the meantime,  I noticed the readme says both

"Certified against Flocker 1.7.0"
and
"This driver has been tested against Flocker 1.4.0."

Could you remove the reference to 1.4.0?  Also, could you add this note at the top of the repo so that people see it first?

Also, do you think that you could set up a CI system for testing the driver against new version?  Like outlined here: https://docs.clusterhq.com/en/1.8.0/gettinginvolved/plugins/building-driver.html#certifying-your-driver

Thanks!

Michael

**Comment by stmcginnis** [comment]
Good catch Michael, I will get rid of that inconsistency.

I've been working towards setting up a CI reporting results, but there are
many challenges with that, especially with the way systems are set up right
now. I am hoping to have something in place soon.
