### ISSUE TITLE
Fibre channel connectivity

### ISSUE THREAD

**Issue by philippe-rero** [dellstorage/storagecenter-flocker-driver#3]
Hi, 

We are highly interested in the Fibre Channel connectivity feature. Do you have any plan on the availability of this feature?

Best regards
PHiLippe

**Comment by jpreddy-modeln** [comment]
Hi,

We are also need this feature. We have TWO storages with fibre connectivity and planning to use docker.

Thanks,
Jaipal

**Comment by stmcginnis** [comment]
That functionality is not likely to be added with flocker basically being no longer supported.
